---
- name: consul clients
  hosts: clients
  remote_user: root

  tasks:
    - name: Make sure consul is running
      systemd:
        state: started
        enabled: yes
        name: consul
    - name: create dnsmasq.d directory
      file:
        state: directory
        path: /etc/dnsmasq.d
    - name: create dnsmasq config
      copy:
        dest: /etc/dnsmasq.d/10-consul
        content: |
          server=/consul/{{ ansible_eth1.ipv4.address }}#8600
          listen-address={{ ansible_eth1.ipv4.address }}
          interface=eth1
          bind-interfaces
    - name: install dnsmasq
      apt:
        name: dnsmasq
        state: present
    - name: Make sure dnsmasq is started
      systemd:
        state: started
        enabled: yes
        name: dnsmasq
    - name: create nomad client config
      copy:
        dest: /etc/nomad.d/client.hcl
        content: |
          name = "{{ dc }}-client-{{ groups['clients'].index(inventory_hostname) }}"
          client {
            enabled = true
            node_class = "worker"
            network_interface = "eth1"
            server_join {
              retry_join = ["{{ servers_private_ip_addresses[0] }}"]
              retry_max = 3
              retry_interval = "15s"
            }
            host_network "public" {
              interface = "eth0"
              cidr      = "{{ ansible_eth0.ipv4.address }}/32"
            }
          }
          plugin "docker" {
            config {
              volumes {
                enabled = true
              }
            }
          }
    - name: Make sure nomad is running
      systemd:
        state: started
        enabled: yes
        name: nomad
