---
- name: consul servers
  hosts: servers
  remote_user: root

  tasks:
    - name: create consul server config
      copy:
        dest: /etc/consul.d/server.hcl
        owner: consul
        group: consul
        mode: '640'
        content: |
          server = true
          bootstrap_expect = 3
          ui = true
    - name: Make sure consul is running
      systemd:
        state: started
        enabled: yes
        name: consul
    - name: Update resolved
      copy:
        dest: /etc/systemd/resolved.conf
        content: |
          [Resolve]
          DNS={{ ansible_eth1.ipv4.address }}
          Domains=~consul
    - name: Make sure systemd-resolved is restarted
      systemd:
        state: restarted
        enabled: yes
        name: systemd-resolved
    - name: iptables udp for consul
      command: iptables -t nat -A OUTPUT -d {{ ansible_eth1.ipv4.address }} -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
    - name: iptables tcp for consul
      command: iptables -t nat -A OUTPUT -d {{ ansible_eth1.ipv4.address }} -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
    - name:  create nomad server config
      copy:
        dest: /etc/nomad.d/server.hcl
        content: |
          name = "{{ dc }}-server-{{ groups['servers'].index(inventory_hostname) }}"
          server {
            enabled = true
            bootstrap_expect = 3
            encrypt = "{{ nomad_encrypt }}"
            server_join {
              retry_join = ["{{ servers_private_ip_addresses[0] }}","{{ servers_private_ip_addresses[1] }}","{{ servers_private_ip_addresses[2] }}"]
              retry_max = 3
              retry_interval = "15s"
            }
          }
    - name: Make sure nomad is running
      systemd:
        state: started
        enabled: yes
        name: nomad
    - name: nomad cli
      copy:
        dest: /root/run.sh
        mode: '700'
        content: |
          nomad job run -address http://{{ ansible_eth1.ipv4.address }}:4646 $1
    - name: download datadog install script
      get_url:
        url: https://s3.amazonaws.com/dd-agent/scripts/install_script.sh
        dest: /tmp/install_dd.sh
        mode: '700'
    - name: install datadog agent
      shell: /tmp/install_dd.sh
      environment:
        DD_AGENT_MAJOR_VERSION: 7
        DD_SITE: datadoghq.com
        DD_INSTALL_ONLY: true
        DD_API_KEY: "{{ datadog_api_key }}"
    - name: create datadog consul config dir
      become: true
      become_user: dd-agent
      file:
        state: directory
        path: /etc/datadog-agent/conf.d/consul.d
    - name: create datadog consul config
      copy:
        dest: /etc/datadog-agent/conf.d/consul.d/conf.yaml
        content: |
          init_config:

          instances:
            - url: http://127.0.0.1:8500

          logs:
            - type: file
              path: /var/log/consul/*.log
              source: consul
              service: consul server
            - type: file
              path: /var/log/nomad/*.log
              source: nomad
              service: nomad server
    - name: add datadog config
      copy:
        dest: /etc/datadog-agent/datadog.yaml
        content: |
          api_key: {{ datadog_api_key }}
          hostname: {{ dc }}-server-{{ groups['servers'].index(inventory_hostname) }}
          bind_host: {{ ansible_eth1.ipv4.address }}
          logs_enabled: true
          logs_config:
            use_tcp: true
    - name: datadog user root
      command: usermod -a -G root dd-agent
    - name: datadog user consul
      command: usermod -a -G consul dd-agent
    - name: Make sure datadog agent is running
      systemd:
        state: started
        enabled: yes
        name: datadog-agent
